# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name=b'Book Name')),
                ('author', models.CharField(default=b'', max_length=100, verbose_name=b'Author')),
                ('description', models.TextField(default=b'', verbose_name=b'Description')),
                ('date_published', models.DateField(null=True, verbose_name=b'Published Date')),
                ('book_url', models.URLField(default=b'', verbose_name=b'Book URL')),
                ('book_cover_image', models.ImageField(default=b'', upload_to=b'books', verbose_name=b'Cover Image')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
