# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gldemo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_url',
        ),
    ]
